Wip

diff --git a/tests/test_expandseq b/tests/test_expandseq
--- a/tests/test_expandseq
+++ b/tests/test_expandseq
@@ -221,6 +221,10 @@ while true; do
     echo --- Test $i of $NUM_TESTS ---
     echo --- Test $i --- $cmd ${args[@]} --- >> $TEST_DIR/$TEST_OUT_FILENAME
     $cmd ${args[@]} >> $TEST_DIR/$TEST_OUT_FILENAME 2>&1
+    retVal=$?
+    if [ $retVal -ne 0 ]; then
+        echo "$cmd returned non-zero error code: $retVal" >> $TEST_DIR/$TEST_OUT_FILENAME 2>&1
+    fi
     i=$(expr $i + 1)
 done
 set +f # Turn globbing back on
